# Dependencies
markdown: redcarpet2
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Music is Math
tagline: ''
description: 'David Hartunian\'s personalsi te and blog'
url: http://www.musicismath.net
baseurl: http://www.musicismath.net/

author:
  name: 'David Hartunian'
  url: https://twitter.com/musicismath

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/dhartunian/dhartunian.github.io
