# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Music is Math
description: "David Hartunian's personal site and blog"
url: http://www.musicismath.net
baseurl: http://www.musicismath.net/

author:
  name: 'David Hartunian'
  url: https://twitter.com/musicismath

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/dhartunian/dhartunian.github.io
