# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Music is Math
tagline:          ''
description:      'David Hartunian\'s personal site and blog'
url:              http://www.musicismath.net
baseurl:          /

author:
  name:           'David Hartunian'
  url:            https://twitter.com/musicismath

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dhartunian/dhartunian.github.io
